name: "Build Preview"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install fonts
        run: make -B fonts
      - name: Run Tectonic
        run: make -B build
      - name: Upload PDFs
        uses: actions/upload-artifact@v2
        with:
          name: PDFs
          path: "*.pdf"
