name: "Build Preview"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install fonts
        run: make prepare
      - name: Run Tectonic
        run: make build
      - name: Upload PDFs
        uses: actions/upload-artifact@v2
        with:
          name: PDFs
          path: "*.pdf"
